name: CI

on:
  # push:
  #   branches: [ "main" ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Pytorch nightly is published around 5 hours after midnight PT
    - cron:  "30 13 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-onnx-survey:
    strategy:
      fail-fast: false
      matrix:
        opset: [9, 10, 11, 12, 13, 14, 15, 16, 17]
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          bash install.sh
      - name: Run survey
        run: |
          export TORCH_ONNX_EXPERIMENTAL_RUNTIME_TYPE_CHECK=ERRORS
          python op_matrix/onnx_op_survey.py --opset ${{ matrix.opset }}
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: op_survey_results
          path: output/op_survey_opset_${{ matrix.opset }}.json
          retention-days: 14
  run-fx-survey:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          bash install.sh
      - name: Run survey
        run: |
          python op_matrix/fx_op_survey.py
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: op_survey_results
          path: output/op_survey_fx.json
          retention-days: 14

  run-jit-survey:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          bash install.sh
      - name: Run survey
        run: |
          python op_matrix/jit_op_survey.py
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: op_survey_results
          path: output/op_survey_jit.json
          retention-days: 14
