name: CI

on:
  # push:
  #   branches: [ "main" ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Pytorch nightly is published around 5 hours after midnight PT
    - cron:  "30 13 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-onnx-survey:
    strategy:
      fail-fast: false
      matrix:
        opset: [17]
        os: ["macos-latest"]
        # Disable "ubuntu-latest" for now because it still has non-held errors
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          bash install.sh
      - name: Run survey
        run: |
          export TORCH_ONNX_EXPERIMENTAL_RUNTIME_TYPE_CHECK=ERRORS
          python op_matrix/onnx_op_survey.py --opset ${{ matrix.opset }}
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: op_survey_results_${{ matrix.opset }}
          path: output/op_survey_opset_${{ matrix.opset }}.json
          retention-days: 14

  run-onnx-dynamo-survey:
    runs-on: "macos-latest"
    timeout-minutes: 800
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          bash install.sh
      - name: Run survey
        run: |
          python op_matrix/onnx_dynamo_op_survey.py
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: op_survey_results_dynamo
          path: output/onnx_dynamo_op_survey.json
          retention-days: 14
