name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-onnx-survey:
    strategy:
      fail-fast: false
      matrix:
        opset: [17]

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          bash install.sh
      - name: Run survey
        run: |
          export TORCH_ONNX_EXPERIMENTAL_RUNTIME_TYPE_CHECK=ERRORS
          python op_matrix/onnx_op_survey.py --opset ${{ matrix.opset }} --debug

      # Build visualization
      - name: Process data for visualization
        run: |
          python op_matrix/process_data_for_visualization.py --input_dir output/ --output op-vis/src/data/op_survey.json
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: 'op-vis/package-lock.json'
      - name: Build react app
        run: npm ci --legacy-peer-deps
        working-directory: 'op-vis'
      - run: npm run build
        working-directory: 'op-vis'

  test-onnx-dynamo-survey:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          bash install.sh
      - name: Run survey
        run: |
          python op_matrix/onnx_dynamo_op_survey.py --debug

  test-jit-survey:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          bash install.sh
      - name: Run survey
        run: |
          python op_matrix/jit_op_survey.py --debug
